window.HANFANG_DATA = {
  ingredients: [
    { id: 'I01', name: '百合', mark: '百', group: '根莖種仁' },
    { id: 'I02', name: '白木耳', mark: '耳', group: '菌菇' },
    { id: 'I03', name: '山藥', mark: '山', group: '根莖種仁' },
    { id: 'I04', name: '生薑', mark: '薑', group: '辛香' },
    { id: 'I05', name: '昆布', mark: '昆', group: '海味' },
    { id: 'I06', name: '小茴香', mark: '茴', group: '辛香' },
    { id: 'I07', name: '八角', mark: '八', group: '辛香' },
    { id: 'I08', name: '龍眼肉', mark: '桂', group: '果實花葉' },
    { id: 'I09', name: '枸杞子', mark: '杞', group: '果實花葉' },
    { id: 'I10', name: '烏梅', mark: '梅', group: '果實花葉' },
    { id: 'I11', name: '紅棗', mark: '棗', group: '果實花葉' },
    { id: 'I12', name: '山楂', mark: '楂', group: '果實花葉' },
    { id: 'I13', name: '花椒', mark: '椒', group: '辛香' },
    { id: 'I14', name: '芡實', mark: '芡', group: '根莖種仁' },
    { id: 'I15', name: '蓮子', mark: '蓮', group: '根莖種仁' },
    { id: 'I16', name: '赤小豆', mark: '豆', group: '根莖種仁' },
    { id: 'I17', name: '薏苡仁', mark: '薏', group: '根莖種仁' },
    { id: 'I18', name: '菊花', mark: '菊', group: '果實花葉' },
    { id: 'I19', name: '薄荷', mark: '荷', group: '果實花葉' },
    { id: 'I20', name: '陳皮', mark: '陳', group: '果實花葉' },
  ],
  recipes: [
    {
      id: 'R01', title: '枸杞紅棗茶', category: '飲品', minutes: 15, servings: '2 杯',
      ingredientIds: ['I09', 'I11'], allergens: [], tone: 'coral',
      description: '果香溫潤，乾果本身的甜味就很剛好。',
      ingredients: ['紅棗 6 顆', '枸杞 10 g', '水 600 ml'],
      steps: ['紅棗洗淨後劃開，和水一起入鍋。', '小火煮 10 分鐘，加入枸杞。', '再煮 3 分鐘，放溫後飲用。'],
    },
    {
      id: 'R02', title: '菊花枸杞茶', category: '飲品', minutes: 8, servings: '2 杯',
      ingredientIds: ['I18', 'I09'], allergens: [], tone: 'gold',
      description: '一壺清淡花香，適合想快速完成的午後。',
      ingredients: ['乾菊花 4 g', '枸杞 6 g', '熱水 600 ml'],
      steps: ['菊花與枸杞快速沖洗。', '加入約 90°C 熱水。', '浸泡 5 分鐘後濾飲。'],
    },
    {
      id: 'R03', title: '烏梅山楂飲', category: '飲品', minutes: 25, servings: '3 杯',
      ingredientIds: ['I10', 'I12'], allergens: [], tone: 'plum',
      description: '酸香醒味，可溫飲也可放涼。',
      ingredients: ['烏梅 3 顆', '山楂 8 g', '水 800 ml', '糖 10 g（可省略）'],
      steps: ['烏梅與山楂沖洗乾淨。', '加水後小火煮 20 分鐘。', '試味後再決定是否加糖。'],
    },
    {
      id: 'R04', title: '桂圓紅棗飲', category: '飲品', minutes: 15, servings: '2 杯',
      ingredientIds: ['I08', 'I11'], allergens: [], tone: 'amber',
      description: '桂圓與紅棗帶出自然甜香，不需另外調味。',
      ingredients: ['龍眼肉 12 g', '紅棗 4 顆', '水 600 ml'],
      steps: ['紅棗洗淨劃開。', '和龍眼肉、水一起入鍋。', '小火煮 12 分鐘即可。'],
    },
    {
      id: 'R05', title: '陳皮生薑茶', category: '飲品', minutes: 12, servings: '2 杯',
      ingredientIds: ['I20', 'I04'], allergens: [], tone: 'sage',
      description: '柑橘皮香與薑的辛香，簡單俐落。',
      ingredients: ['陳皮 2 g', '生薑 10 g', '水 600 ml'],
      steps: ['薑切薄片，陳皮快速沖洗。', '加水煮 8 分鐘。', '熄火再燜 2 分鐘。'],
    },
    {
      id: 'R06', title: '薄荷檸檬飲', category: '飲品', minutes: 10, servings: '2 杯',
      ingredientIds: ['I19'], allergens: [], tone: 'mint',
      description: '清新的草本與柑橘氣味，可溫飲或冷藏。',
      ingredients: ['乾薄荷 2 g或鮮葉 10 片', '檸檬 2 片', '水 600 ml'],
      steps: ['薄荷用熱水浸泡 5 分鐘。', '放涼片刻後加入檸檬。', '直接飲用或冷藏。'],
    },
    {
      id: 'R07', title: '白木耳蓮子紅棗羹', category: '甜湯', minutes: 60, servings: '4 碗',
      ingredientIds: ['I02', 'I15', 'I11'], allergens: [], tone: 'peach',
      description: '軟糯有層次的家庭甜湯，預設不額外加糖。',
      ingredients: ['乾白木耳 20 g', '蓮子 40 g', '紅棗 4 顆', '水 1.2 L'],
      steps: ['白木耳與蓮子分別泡發，白木耳剪小朵。', '白木耳和蓮子煮 40 分鐘。', '加入紅棗再煮 10 分鐘。'],
    },
    {
      id: 'R08', title: '百合白木耳雪梨羹', category: '甜湯', minutes: 45, servings: '4 碗',
      ingredientIds: ['I01', 'I02'], allergens: [], tone: 'linen',
      description: '雪梨的清甜融進柔軟白木耳。',
      ingredients: ['乾百合 20 g', '乾白木耳 15 g', '梨 1 顆', '水 1 L'],
      steps: ['百合與白木耳分別泡發。', '白木耳先煮 25 分鐘。', '加入百合與梨塊再煮 12 分鐘。'],
    },
    {
      id: 'R09', title: '山藥芡實甜湯', category: '甜湯', minutes: 45, servings: '4 碗',
      ingredientIds: ['I03', 'I14'], allergens: [], tone: 'sand',
      description: '口感樸實柔和，保留食材原味。',
      ingredients: ['新鮮食用山藥 250 g', '芡實 40 g', '水 1 L', '糖 10 g（可省略）'],
      steps: ['芡實先浸泡 4 小時。', '加水煮芡實 25 分鐘。', '加入山藥塊續煮約 15 分鐘。'],
    },
    {
      id: 'R10', title: '桂圓蓮子湯', category: '甜湯', minutes: 40, servings: '4 碗',
      ingredientIds: ['I08', 'I15'], allergens: [], tone: 'amber',
      description: '蓮子柔軟、桂圓清甜，是簡單的餐後小碗。',
      ingredients: ['蓮子 50 g', '龍眼肉 15 g', '水 1 L'],
      steps: ['蓮子浸泡後加水煮 25 分鐘。', '加入龍眼肉。', '再煮 8 分鐘即可。'],
    },
    {
      id: 'R11', title: '薏仁赤小豆粥', category: '粥品', minutes: 60, servings: '4 碗',
      ingredientIds: ['I17', 'I16'], allergens: [], tone: 'clay',
      description: '需要預先浸泡，適合週末慢慢煮一鍋。',
      ingredients: ['薏苡仁 60 g', '赤小豆 60 g', '白米 40 g', '水 1.2 L'],
      steps: ['薏苡仁與赤小豆浸泡至少 4 小時。', '和白米、水一起入鍋。', '小火煮至所有食材完全軟爛。'],
    },
    {
      id: 'R12', title: '山藥芡實粥', category: '粥品', minutes: 50, servings: '4 碗',
      ingredientIds: ['I03', 'I14'], allergens: [], tone: 'sage',
      description: '細緻的米粥裡保留山藥小塊口感。',
      ingredients: ['白米 80 g', '芡實 30 g', '新鮮食用山藥 150 g', '水 1.2 L'],
      steps: ['芡實浸泡後和白米先煮 30 分鐘。', '加入山藥丁。', '續煮至山藥與米粒都軟熟。'],
    },
    {
      id: 'R13', title: '桂圓紫米粥', category: '粥品', minutes: 55, servings: '4 碗',
      ingredientIds: ['I08'], allergens: [], tone: 'plum',
      description: '紫米色澤深潤，桂圓提供淡淡甜味。',
      ingredients: ['紫米 80 g', '白米 40 g', '龍眼肉 15 g', '水 1.2 L'],
      steps: ['紫米先浸泡 2 小時。', '與白米煮 40 分鐘。', '加入龍眼肉再煮 8 分鐘。'],
    },
    {
      id: 'R14', title: '百合蓮子小米粥', category: '粥品', minutes: 40, servings: '4 碗',
      ingredientIds: ['I01', 'I15'], allergens: [], tone: 'gold',
      description: '小米清香，百合與蓮子帶來柔軟口感。',
      ingredients: ['小米 80 g', '蓮子 40 g', '乾百合 20 g', '水 1 L'],
      steps: ['蓮子先煮 15 分鐘。', '加入小米與泡好的百合。', '續煮至所有食材軟熟。'],
    },
    {
      id: 'R15', title: '枸杞南瓜燕麥粥', category: '粥品', minutes: 25, servings: '3 碗',
      ingredientIds: ['I09'], allergens: [], tone: 'pumpkin',
      description: '南瓜自然甜，適合忙碌早晨。',
      ingredients: ['燕麥片 60 g', '南瓜 200 g', '枸杞 8 g', '水 800 ml'],
      steps: ['南瓜切塊煮軟，壓碎一部分。', '加入燕麥煮 5 分鐘。', '最後加入枸杞煮 2 分鐘。'],
    },
    {
      id: 'R16', title: '山藥枸杞雞湯', category: '主餐', minutes: 55, servings: '4 碗',
      ingredientIds: ['I03', 'I09', 'I04'], allergens: [], tone: 'sage',
      description: '清爽家常雞湯，食材與步驟都很直觀。',
      ingredients: ['雞肉 500 g', '新鮮食用山藥 300 g', '枸杞 10 g', '薑 3 片', '水 1.5 L'],
      steps: ['雞肉汆燙後和薑片煮 30 分鐘。', '加入山藥煮 15 分鐘。', '最後加入枸杞煮 3 分鐘。'],
    },
    {
      id: 'R17', title: '昆布山藥蔬菜湯', category: '主餐', minutes: 35, servings: '4 碗',
      ingredientIds: ['I05', 'I03'], allergens: [], tone: 'mint',
      description: '清淡蔬菜湯底，最後只需少量調味。',
      ingredients: ['乾昆布 10 g', '山藥 200 g', '高麗菜 150 g', '菇類 100 g', '水 1.2 L'],
      steps: ['昆布依包裝說明泡開並切段。', '所有食材加水煮約 25 分鐘。', '起鍋前少量調味。'],
    },
    {
      id: 'R18', title: '陳皮蘿蔔雞湯', category: '主餐', minutes: 50, servings: '4 碗',
      ingredientIds: ['I20', 'I04'], allergens: [], tone: 'linen',
      description: '蘿蔔清甜，陳皮只留下淡淡柑橘香。',
      ingredients: ['雞腿肉 400 g', '白蘿蔔 400 g', '陳皮 2 g', '薑 3 片', '水 1.3 L'],
      steps: ['雞肉先汆燙。', '所有食材一起小火煮 40 分鐘。', '起鍋前少量調味。'],
    },
    {
      id: 'R19', title: '小茴香八角滷豆干', category: '主餐', minutes: 30, servings: '4 人',
      ingredientIds: ['I06', 'I07', 'I04'], allergens: ['soy'], tone: 'amber',
      description: '香料份量克制，適合作為一盤家常小菜。',
      ingredients: ['豆干 400 g', '八角 1 顆', '小茴香 1 茶匙', '薑 3 片', '醬油 40 ml', '水 500 ml'],
      steps: ['所有食材入鍋煮滾。', '轉小火滷 20 分鐘。', '關火浸泡 10 分鐘再盛盤。'],
    },
    {
      id: 'R20', title: '花椒薑絲蒸魚', category: '主餐', minutes: 20, servings: '3 人',
      ingredientIds: ['I13', 'I04'], allergens: ['fish'], tone: 'coral',
      description: '花椒的麻香與薑絲很適合清蒸魚片。',
      ingredients: ['魚片 350 g', '薑絲 15 g', '花椒 1/2 茶匙', '蔥 1 支', '油 1 茶匙'],
      steps: ['魚片鋪薑絲，水滾後蒸 8–10 分鐘至熟。', '少量油爆香花椒。', '將花椒油淋在魚上，撒上蔥絲。'],
    },
  ],
  stores: [
    { id: 'S01', city: '台北市', district: '大同區', name: '迪化街乾貨商圈', type: '乾貨／食品級漢方', address: '台北市大同區迪化街一段', availability: 'possible', source: '示範資料' },
    { id: 'S02', city: '台北市', district: '中正區', name: '南門市場', type: '南北雜貨／市場', address: '台北市中正區羅斯福路一段8號', availability: 'possible', source: '臺北市市場資料' },
    { id: 'S03', city: '台中市', district: '中區', name: '第二市場', type: '公有市場', address: '台中市中區三民路二段87號', availability: 'possible', source: '臺中市市場資料' },
    { id: 'S04', city: '台中市', district: '西區', name: '第五市場', type: '公有市場', address: '台中市西區大明街9號', availability: 'possible', source: '臺中市市場資料' },
    { id: 'S05', city: '高雄市', district: '三民區', name: '三鳳中街商圈', type: '南北貨／乾貨', address: '高雄市三民區三鳳中街', availability: 'possible', source: '高雄市商圈資料' },
    { id: 'S06', city: '高雄市', district: '三民區', name: '三民第一公有市場周邊', type: '公有市場', address: '高雄市三民區三民街', availability: 'possible', source: '高雄市市場資料' },
  ],
};
